### ISSUE TITLE
Create a named tag to enable packaging into bioconda

### ISSUE THREAD

**Issue by tdido** [keyuan/ccube#9]
I'd like to generate a bioconda package for ccube, in order to easily include it into a planned pipeline.

Would you be willing to generate a named tag so I can use the resulting release to generate the package?

**Comment by keyuan** [comment]
create a prerelease with tag https://github.com/keyuan/ccube/releases/tag/v1.0-beta.1

**Comment by tdido** [comment]
@keyuan sorry for the bother, the package is almost ready but the builder doesn't accept `-` in the version tag. Any chance you could change it to `.` or `_`, for example?

**Comment by keyuan** [comment]
@tdido will "v1.0_beta.1" work?

**Comment by tdido** [comment]
Yes, that should be fine. Thanks!

**Comment by keyuan** [comment]
https://github.com/keyuan/ccube/releases/tag/v1.0_beta.1

**Comment by tdido** [comment]
Bioconda package is now available: https://anaconda.org/bioconda/r-ccube
